'''
Power System Analysis
Author: 梁飞，单士磊，蒋奕琛
Date: 2021.1.13
本程序仅用于课堂展示
'''

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 299)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(20, 250, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 329, 137))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.typelabel = QtWidgets.QLabel(self.layoutWidget)
        self.typelabel.setObjectName("typelabel")
        self.verticalLayout_3.addWidget(self.typelabel)
        self.Plable = QtWidgets.QLabel(self.layoutWidget)
        self.Plable.setObjectName("Plable")
        self.verticalLayout_3.addWidget(self.Plable)
        self.Qlable = QtWidgets.QLabel(self.layoutWidget)
        self.Qlable.setObjectName("Qlable")
        self.verticalLayout_3.addWidget(self.Qlable)
        self.Vlable = QtWidgets.QLabel(self.layoutWidget)
        self.Vlable.setObjectName("Vlable")
        self.verticalLayout_3.addWidget(self.Vlable)
        self.VoltageLevel = QtWidgets.QLabel(self.layoutWidget)
        self.VoltageLevel.setObjectName("VoltageLevel")
        self.verticalLayout_3.addWidget(self.VoltageLevel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.typetext = QtWidgets.QLineEdit(self.layoutWidget)
        self.typetext.setObjectName("typetext")
        self.verticalLayout.addWidget(self.typetext)
        self.Ptext = QtWidgets.QLineEdit(self.layoutWidget)
        self.Ptext.setObjectName("Ptext")
        self.verticalLayout.addWidget(self.Ptext)
        self.Qtext = QtWidgets.QLineEdit(self.layoutWidget)
        self.Qtext.setObjectName("Qtext")
        self.verticalLayout.addWidget(self.Qtext)
        self.Vtext = QtWidgets.QLineEdit(self.layoutWidget)
        self.Vtext.setObjectName("Vtext")
        self.verticalLayout.addWidget(self.Vtext)
        self.Ktext = QtWidgets.QLineEdit(self.layoutWidget)
        self.Ktext.setObjectName("Ktext")
        self.verticalLayout.addWidget(self.Ktext)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BusTypeLabel = QtWidgets.QLabel(self.layoutWidget)
        self.BusTypeLabel.setObjectName("BusTypeLabel")
        self.verticalLayout_2.addWidget(self.BusTypeLabel)
        self.PLabel = QtWidgets.QLabel(self.layoutWidget)
        self.PLabel.setObjectName("PLabel")
        self.verticalLayout_2.addWidget(self.PLabel)
        self.QLable = QtWidgets.QLabel(self.layoutWidget)
        self.QLable.setObjectName("QLable")
        self.verticalLayout_2.addWidget(self.QLable)
        self.VLable = QtWidgets.QLabel(self.layoutWidget)
        self.VLable.setObjectName("VLable")
        self.verticalLayout_2.addWidget(self.VLable)
        self.KLable = QtWidgets.QLabel(self.layoutWidget)
        self.KLable.setText("")
        self.KLable.setObjectName("KLable")
        self.verticalLayout_2.addWidget(self.KLable)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bus"))
        self.typelabel.setText(_translate("Dialog", " BusType:"))
        self.Plable.setText(_translate("Dialog", "     P:"))
        self.Qlable.setText(_translate("Dialog", "     Q:"))
        self.Vlable.setText(_translate("Dialog", "     V:"))
        self.VoltageLevel.setText(_translate("Dialog", "     K："))
        self.BusTypeLabel.setText(_translate("Dialog", "PQ or PV"))
        self.PLabel.setText(_translate("Dialog", "MW"))
        self.QLable.setText(_translate("Dialog", "Mvar"))
        self.VLable.setText(_translate("Dialog", "kv"))

        self.typetext.setToolTip('You can only type "PQ" or "PV" here.')
        self.typetext.setStatusTip('You can only type "PQ" or "PV" here.')
        self.Ptext.setToolTip('Set the active power of this bus.')
        self.Ptext.setStatusTip('Set the active power of this bus.')
        self.Qtext.setToolTip('Set the reactive power of this bus.')
        self.Qtext.setStatusTip('Set the reactive power of this bus.')
        self.Vtext.setToolTip('Set the voltage of this bus.')
        self.Vtext.setStatusTip('Set the voltage of this bus.')
        self.Ktext.setToolTip('Set the voltage level of this bus.')
        self.Ktext.setStatusTip('Set the voltage level of this bus.')


