'''
Power System Analysis
Author: 梁飞，单士磊，蒋奕琛
Date: 2021.1.13
本程序仅用于课堂展示
'''

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LineParaUnkown(object):
    def setupUi(self, LineParaUnkown):
        LineParaUnkown.setObjectName("LineParaUnkown")
        LineParaUnkown.resize(481, 359)
        self.buttonBox = QtWidgets.QDialogButtonBox(LineParaUnkown)
        self.buttonBox.setGeometry(QtCore.QRect(120, 310, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(LineParaUnkown)
        self.widget.setGeometry(QtCore.QRect(20, 60, 389, 169))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineTypeEdit = QtWidgets.QLineEdit(self.widget)
        self.lineTypeEdit.setObjectName("lineTypeEdit")
        self.verticalLayout_2.addWidget(self.lineTypeEdit)
        self.distenceEdit = QtWidgets.QLineEdit(self.widget)
        self.distenceEdit.setObjectName("distenceEdit")
        self.verticalLayout_2.addWidget(self.distenceEdit)
        self.reqEdit = QtWidgets.QLineEdit(self.widget)
        self.reqEdit.setObjectName("reqEdit")
        self.verticalLayout_2.addWidget(self.reqEdit)
        self.nEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.nEdit_5.setObjectName("nEdit_5")
        self.verticalLayout_2.addWidget(self.nEdit_5)
        self.lengthEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lengthEdit_3.setObjectName("lengthEdit_3")
        self.verticalLayout_2.addWidget(self.lengthEdit_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.locationEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.locationEdit_6.setObjectName("locationEdit_6")
        self.verticalLayout_3.addWidget(self.locationEdit_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_4.addWidget(self.label_13)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)

        self.retranslateUi(LineParaUnkown)
        self.buttonBox.accepted.connect(LineParaUnkown.accept)
        self.buttonBox.rejected.connect(LineParaUnkown.reject)
        QtCore.QMetaObject.connectSlotsByName(LineParaUnkown)

    def retranslateUi(self, LineParaUnkown):
        _translate = QtCore.QCoreApplication.translate
        LineParaUnkown.setWindowTitle(_translate("LineParaUnkown", "Line"))
        self.label.setText(_translate("LineParaUnkown", " lineType:"))
        self.label_2.setText(_translate("LineParaUnkown", " distance:"))
        self.label_3.setText(_translate("LineParaUnkown", "      req:"))
        self.label_4.setText(_translate("LineParaUnkown", "        n:"))
        self.label_5.setText(_translate("LineParaUnkown", "   length:"))
        self.label_6.setText(_translate("LineParaUnkown", " Location:"))
        self.label_7.setText(_translate("LineParaUnkown", "eg. LGJ-300/50"))
        self.label_12.setText(_translate("LineParaUnkown", "m"))
        self.label_8.setText(_translate("LineParaUnkown", "mm"))
        self.label_10.setText(_translate("LineParaUnkown", "km"))
        self.label_11.setText(_translate("LineParaUnkown", "(x,y)"))

        self.distenceEdit.setToolTip('Set the mean geometrical distance.')
        self.distenceEdit.setStatusTip('Set the mean geometrical distance.')
        self.reqEdit.setToolTip('Set the equivalent radius')
        self.reqEdit.setStatusTip('Set the equivalent radius')
        self.nEdit_5.setToolTip('Set the number of divided line.')
        self.nEdit_5.setStatusTip('Set the number of divided line.')
        self.lengthEdit_3.setToolTip('Set the length between two buses.')
        self.lengthEdit_3.setStatusTip('Set the length between two buses.')
        self.locationEdit_6.setToolTip('Set the location of the line.')
        self.locationEdit_6.setStatusTip('Set the location of the line.')


